In [1]:
from core.gradient_descent import wolfe_conditions_search, point_number_terminate_condition, fixed_step_search
%load_ext autoreload
%autoreload 2

from core.high_order_optimization import *
from core.optimizer_evaluator import *
from core.utils import *
from core.visualizer import *
import numpy as np

# Вычисление $\nabla^2 f$: Аналитически, численно

In [2]:
q = QuadraticForm(np.array([
    [10, 2],
    [2, 2]
]))

In [3]:
x = np.array([3, 4])
q.gradient_function()(x)

array([76, 28])

In [4]:
symmetric_gradient_computer(q)(x)

array([76., 28.])

In [5]:
q.hessian_function()(x)

array([[20,  4],
       [ 4,  4]])

In [6]:
symmetric_hessian_computer(q)(x)

array([[20.00000165,  3.99985822],
       [ 3.99985822,  3.99992928]])