In [44]:
from core.gradient_descent import wolfe_conditions_search, point_number_terminate_condition, fixed_step_search
%load_ext autoreload
%autoreload 2

from core.high_order_optimization import *
from core.optimizer_evaluator import *
from core.utils import *
from core.visualizer import *
import numpy as np

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


# Нелинейная регрессия

Минимизируем функцию, представленную в виде $$
S(\beta) = \sum_{i = 0}^n r_i(\beta)^2
$$

## Gauss-Newton метод



## DogLeg метод

Подход trust-region, строим квадратичную модель, стандартным образом$^*$ расширяем/сужаем trust region.

Минимизация происходит так:
- Для положительно определённой формы точка Коши находится строго внутри
-


In [45]:
f1 = lambda x: np.exp(x[0])
f2 = lambda x: np.sin(x[0])
f3 = lambda x: np.exp(-(x[0] + 1))
fs = [f1, f2, f3]

df1 = lambda x: np.array([np.exp(x[0])])
df2 = lambda x: np.array([np.cos(x[0])])
df3 = lambda x: np.array([-np.exp(-(x[0] + 1))])
dfs = [df1, df2, df3]

x0 = np.array([10])

termination = lambda f, points: len(points) > 20

p1 = gauss_newton(fs, dfs, x0, termination)
p2 = gauss_newton_with_approx_grad(fs, x0, termination)

print(f"symbolic grad argmin = {p1[-1]}, approx grad argmin = {p2[-1]}")

symbolic grad argmin = [-0.30823297], approx grad argmin = [-0.3083785]


In [35]:
f1 = generate_positive_definite_quadratic_form(2, 10, random_orthonormal_basis)
f2 = generate_positive_definite_quadratic_form(2, 12, random_orthonormal_basis)

df1 = f1.gradient_function()
df2 = f2.gradient_function()

dogleg([f1, f2], [df1, df2], 10, wolfe_conditions_search(0.1, 0.9), np.array([-5.0, 5.0]), lambda f, ps: f(ps[-1]) < 1e-5)

sd step = [ 0.6746426  -0.73814454], current = [-5.  5.]
rho = 0.9400486851509245
trusted = 2
sd step = [ 1.35226729 -1.473558  ], current = [-4.3253574   4.26185546]
rho = 0.9028530610051766
trusted = 4
sd step = [ 2.72444055 -2.9287239 ], current = [-2.97309012  2.78829746]
rho = 15.786736445294656
trusted = 8
gn step
rho = 0.9375000000000001
trusted = 10
gn step
rho = 0.9375000000000001
trusted = 10
gn step
rho = 0.9375000000000001
trusted = 10


[array([-5.,  5.]),
 array([-4.3253574 ,  4.26185546]),
 array([-2.97309012,  2.78829746]),
 array([-0.24864957, -0.14042645]),
 array([-0.12432478, -0.07021322]),
 array([-0.06216239, -0.03510661]),
 array([-0.0310812 , -0.01755331])]